"""empty message

Revision ID: 6a466ff0a041
Revises: f62e2d0a719b
Create Date: 2018-08-25 12:36:20.238829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a466ff0a041'
down_revision = 'f62e2d0a719b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mini_avatar', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('real_avatar', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'real_avatar')
    op.drop_column('users', 'mini_avatar')
    # ### end Alembic commands ###
