"""empty message

Revision ID: 9943558db952
Revises: 6a466ff0a041
Create Date: 2018-08-25 16:29:11.796778

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9943558db952'
down_revision = '6a466ff0a041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('file_name', sa.String(length=64), nullable=True))
    op.drop_column('users', 'real_avatar')
    op.drop_column('users', 'mini_avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mini_avatar', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('users', sa.Column('real_avatar', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('users', 'file_name')
    # ### end Alembic commands ###
